version: "3"
services:
  mysql:
    image: mysql:latest
    command: [--default-authentication-plugin=mysql_native_password]
    restart: always
    ports:
      - '127.0.0.1:3306:3306'
    environment:  
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=task 
      - MYSQL_PASSWORD=root 
      - MYSQL_USER=root
    volumes:
      - ./db:/var/lib/mysql